# Generated by Django 4.1.7 on 2024-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elder_id", models.IntegerField(max_length=10)),
                ("elder_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.IntegerField()),
                ("elder_code", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
