# Generated by Django 5.1.4 on 2024-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_code",
            field=models.IntegerField(default="default_code", unique=True),
        ),
        migrations.AlterField(
            model_name="elder",
            name="elder_id",
            field=models.IntegerField(default="default_code", unique=True),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="elder_code",
            field=models.IntegerField(default="default_code", unique=True),
        ),
    ]
