# Generated by Django 4.1.7 on 2024-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_id",
            field=models.IntegerField(),
        ),
    ]
