# Generated by Django 5.1.4 on 2024-12-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
