# Generated by Django 5.1.4 on 2024-12-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0002_alter_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
