# Generated by Django 5.1.4 on 2024-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0002_alter_elder_elder_code_alter_elder_elder_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_code",
            field=models.IntegerField(default="0000", unique=True),
        ),
        migrations.AlterField(
            model_name="elder",
            name="elder_id",
            field=models.IntegerField(default="00000", unique=True),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="elder_code",
            field=models.IntegerField(default="0000", unique=True),
        ),
    ]
