# Generated by Django 5.1.4 on 2024-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0002_alter_elder_elder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('recurrence', models.CharField(choices=[('none', '繰り返さない'), ('daily', '日ごと'), ('weekly', '週ごと'), ('monthly', '月ごと')], default='none', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('completion', models.BooleanField(default=False)),
                ('silver_code', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
