# Generated by Django 5.1.4 on 2024-12-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0003_alter_elder_elder_code_alter_elder_elder_id_and_more"),
        ("careLink", "0003_alter_schedule_time"),
    ]

    operations = []
