# Generated by Django 5.1.4 on 2024-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0003_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_code",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="elder",
            name="elder_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="elder_code",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family_id",
            field=models.IntegerField(unique=True),
        ),
    ]
