# Generated by Django 5.1.4 on 2024-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0004_merge_20241227_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyuser",
            name="elder_code",
            field=models.IntegerField(default="0000"),
        ),
    ]
