# Generated by Django 5.1.4 on 2025-01-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0005_alter_familyuser_elder_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_images/'),
        ),
    ]
