# Generated by Django 5.1.4 on 2024-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0005_alter_familyuser_elder_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="elder",
            name="elder_name",
            field=models.CharField(default="{elder_code}", max_length=10),
        ),
    ]
