# Generated by Django 5.1.4 on 2025-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0006_schedule_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('date', 'silver_code'), name='unique_image_per_date'),
        ),
    ]
