# Generated by Django 5.1.4 on 2025-01-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careLink', '0007_schedule_unique_image_per_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_image_per_date',
        ),
    ]
