# Generated by Django 5.1.4 on 2024-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0007_alter_elder_elder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_name",
            field=models.CharField(
                default="<django.db.models.fields.IntegerField>", max_length=10
            ),
        ),
    ]
