# Generated by Django 5.1.4 on 2025-01-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0008_alter_elder_elder_name"),
        ("careLink", "0009_remove_schedule_image_familyuser_image"),
    ]

    operations = []
