# Generated by Django 5.1.4 on 2025-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0010_merge_20250120_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elder",
            name="elder_name",
            field=models.CharField(default="ユーザー", max_length=10),
        ),
    ]
