# Generated by Django 5.1.4 on 2025-01-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careLink", "0009_alter_elder_elder_name"),
        ("careLink", "0011_alter_elder_elder_name"),
    ]

    operations = []
